version: '3'
services:
    apache:
        build: .docker/apache
        container_name: my_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf3.4
        depends_on:
          - php

    mysql:
        image: mysql
        container_name: mysql_db
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mysql_db
            MYSQL_USER: mysql_db
            MYSQL_PASSWORD: mysql_db
        command: ["--default-authentication-plugin=mysql_native_password"]

    php:
        build: .docker/php
        container_name: sf3.4_php
        volumes:
          - .:/home/wwwroot/sf3.4
        environment:
          - maildev_host=sf3.4_maildev
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf3.4_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: sf3.4_maildev
        ports:
          - 8001:80
